### ISSUE TITLE
Add Spring Conventions for Javadoc Task

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/javadoc-plugin#2]
This could set defaults for the Javadoc Task (i.e. styling, options, etc)

**Comment by rwinch** [comment]
@wilkinsona I'm curious your thoughts on this.

I'm thinking that I will create a separate conventions plugin that obtains the spring stylesheet and sets it on the Javadoc task. I believe this makes sense so that users can leverage the existing plugins to do aggregate Javadoc. What are your thoughts?

**Comment by wilkinsona** [comment]
That's what I was trying to describe in the second paragraph of [this comment](https://github.com/spring-gradle-plugins/javadoc-plugin/issues/3#issuecomment-601130309), where I said the following:

> An alternative approach would be to split things on the javadoc-plugin side into a piece (base plugin?) that configures the conventions and something on top that triggers consumption by the aggregating project

If we can opt into the Javadoc conventions without also opting into aggregation, there'd be no need to exclude projects from the aggregation.

**Comment by rwinch** [comment]
Thanks. It seems like we are on the same page now. I'm going to proceed with making this a separate plugin named `io.spring.javadoc-conventions`.

**Comment by rwinch** [comment]
@wilkinsona I pushed changes to master to add `io.spring.gradle.javadoc-conventions` plugin. See https://github.com/spring-gradle-plugins/javadoc-plugin#iospringjavadoc-conventions

**Comment by wilkinsona** [comment]
Great stuff. Thanks, @rwinch.
