### ISSUE TITLE
Allow some projects with the javadoc-plugin applied to not be included in the aggregated javadoc

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/javadoc-plugin#3]
In Spring Boot's build we publish two separate sets of javadoc:

- [Gradle Plugin's javadoc](https://docs.spring.io/spring-boot/docs/2.3.0.M1/gradle-plugin/api/)
- [Main javadoc](https://docs.spring.io/spring-boot/docs/2.3.0.M1/api/) aggregated from numerous projects

We want to apply the same conventions to both sets of javadoc, but don't want the Gradle Plugin's javadoc to be included in the main aggregated javadoc. I think this means that I'd like to be able to apply the `javadoc-plugin` across the board (to pick up any conventions for CSS etc) and then to be able to filter the projects that the aggregated javadoc plugin will use.

**Comment by rwinch** [comment]
Thanks for the report @wilkinsona 

I'm thinking we might be able to do this by exposing an extension that allows configuring what projects should be used. It would default to work as is, but would allow configuring any projects you want. Is this something you think would work?

If so, any thoughts on the name of the extension? I believe it might be "bad form" to expose the extension and the task under the same name. Currently the task is named `aggregateJavadoc`. Thoughts?

**Comment by wilkinsona** [comment]
I don't think it needs to be an extension. Some customization on the `aggregateJavadoc` task would be sufficient.

An alternative approach would be to split things on the `javadoc-plugin` side into a piece (base plugin?) that configures the conventions and something on top that triggers consumption by the aggregating project.

**Comment by rwinch** [comment]
I don't think I understand the point on customization of `aggregateJavadoc`. It is just a Javadoc task and is fully customizable. It would mean you'd need to replicate all the logic which means you'd get no benefit. How do you imagine this would look from a consumption point of view?

The second suggestion does not make sense to me either. It seems to imply `javadoc-plugin' is configuring things now. However, it is inverted.

**Comment by wilkinsona** [comment]
It sounds like I've misunderstood the README. I was basing my understanding of the `aggregateJavadoc` task on this description:

> This will create a task named aggregateJavadoc of type Javadoc. The task defaults the source and classpath to aggregate values based on all of the projects that contain the io.spring.javadoc plugin.

It's the "aggregate values based on all of the projects that contain the io.spring.javadoc plugin" that I'd like to be able to filter.

> The second suggestion does not make sense to me either. It seems to imply `javadoc-plugin' is configuring things now. However, it is inverted.

My thinking there was that there could be something like `io.spring.javadoc-base` that applies the conventions for CSS and the like. Assuming that the aggregation side only consumes from projects that contain the `io.spring.javadoc` plugin, you could then benefit from the conventions without being part of the aggregated javadoc.

**Comment by rwinch** [comment]
Hmm..I think we are kind of on the same page but a little confused what you are confused about. Let try and put together a branch with what I had in mind and we can revise.

**Comment by rwinch** [comment]
@wilkinsona I think that this should be resolved via gh-1 See https://github.com/spring-gradle-plugins/javadoc-plugin/issues/1#issuecomment-603526110 Can you give the `0.0.2-SNAPSHOT` a try? Note that you can resolve the SNAPSHOTs from the [Spring plugins-snapshots repository](https://github.com/spring-gradle-plugins/javadoc-plugin#downloading) now.

**Comment by wilkinsona** [comment]
Declaring `implementation` dependencies makes it possible to do what I want but it is more cumbersome than I would like. Rather than having to include every project that I want to be aggregated I'd prefer to be able to exclude those that I don't want to be aggregated. I prefer it this way around as the number of projects that we want to exclude is far smaller than the number of projects that we want to include.

**Comment by rwinch** [comment]
I don't want to add a filter mechanism to the plugin as it is already supported with a more powerful mechanism. I don't find this to be cumbersome:

```groovy
def excluded = ['aggregator', 'module2', 'test-module']
dependencies {
    implementation rootProject.subprojects.findAll { p -> !excluded.contains(p.name) }
}
```

Perhaps I'm missing something?

**Comment by wilkinsona** [comment]
It'll work but it isn't declarative and it requires writing logic that deals with other projects. They're both things that we try to avoid in our `build.gradle` scripts and handle in a plugin instead.

**Comment by wilkinsona** [comment]
Another minor nit with using `implementation` dependencies isn't that it isn't very expressive. If you aren't familiar with how the javadoc aggregation works, it's not clear that dependencies in the `implementation` configuration are what will be aggregated. If a configuration-based approach is needed, using a custom configuration named `aggregatedJavadoc` or the like would make the intent clearer I think.

**Comment by rwinch** [comment]
Adding an exclude mechanism is not something I'd like to do. What happens if a user now wants to modify which projects are included as well?

> It'll work but it isn't declarative and it requires writing logic that deals with other projects. They're both things that we try to avoid in our build.gradle scripts and handle in a plugin instead.

I don't understand this point. How would your proposal differ from this one?

> Another minor nit with using implementation dependencies isn't that it isn't very expressive. If you aren't familiar with how the javadoc aggregation works, it's not clear that dependencies in the implementation configuration are what will be aggregated. If a configuration-based approach is needed, using a custom configuration named aggregatedJavadoc or the like would make the intent clearer I think.

I think this is a fair statement. We could change the configuration name to be something more expressive. Would you mind creating a separate ticket for this?

**Comment by wilkinsona** [comment]
> I don't understand this point. How would your proposal differ from this one?

I'd like to be able to write something like this:

```java
aggregateJavadoc {
    exclude 'aggregator', 'module2', 'test-module'
}
```

Perhaps `exclude` should be named `excludeProject` or similar, but the key thing is that it's entirely declarative and avoids writing logic in a script that iterates over all subproject or similar.

> Would you mind creating a separate ticket for this?

Will do. Thanks.

**Comment by rwinch** [comment]
Thanks for the example. My concern is this a very specific feature which would make it reasonable for users to ask for lots of little knobs that can be solved with minimal code. Adding this feature users could reasonably ask for a feature for excluding by something other than the project name, including additional projects, etc. 

I don't see adding a feature that is so specific that can be done with very little logic. I'm closing this as invalid as it can be accomplished with the changes in gh-1

**Comment by wilkinsona** [comment]
That's disappointing. Allowing Gradle scripts to be declarative is one of the main points of writing a plugin, perhaps the second most important point beyond reuse. We have a genuine need for this in Spring Boot and without it we'll have to ignore Gradle best practices and add some imperative logic to our build scripts or roll our own plugin. Neither of those is desirable. 

Can you please reconsider? I'd be happy to contribute something.

**Comment by rwinch** [comment]
> Can you please reconsider? I'd be happy to contribute something.

I'll reopen as we discuss, but I'd like to avoid needing to add knobs for every conditional a user might have as I think this can be separated from the plugin itself.

Does this help?

```groovy
configurations.aggregateJavadocClasspath {
    exclude module: 'test-module'
    exclude module: 'module2'
}
```

**NOTE:** Updated to use `aggregateJavadocClasspath` since gh-4 is now closed

**Comment by rwinch** [comment]
@wilkinsona Are you able to achieve what you need now? Can this issue be closed?

**Comment by wilkinsona** [comment]
Yes, I think so. With a separate plugin for the conventions allowing aggregation to be opted into separately, I don't think there's a need for exclusions.
